# Generated by Django 4.2.4 on 2023-09-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.BooleanField(default=0)),
                ('department', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
